# Generated by Django 6.0.5 on 2026-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_productvariant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='LEGENDARY', max_length=50),
        ),
    ]
