# Generated by Django 6.0.5 on 2026-06-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_productvariantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantimage',
            options={'ordering': ['-is_primary', 'created_at']},
        ),
    ]
