# Generated by Django 6.0.5 on 2026-07-10 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='returnrequestimage',
            name='return_request',
        ),
        migrations.AlterModelOptions(
            name='adminactivitylog',
            options={},
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_received_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
        migrations.DeleteModel(
            name='ReturnRequestImage',
        ),
    ]
