# Generated by Django 6.0.5 on 2026-07-13 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_remove_orderitem_order_remove_returnrequest_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('offer_type', models.CharField(choices=[('PRODUCT', 'Product Based'), ('CATEGORY', 'Category Based')], max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='adminpanel.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='adminpanel.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer_type', 'is_active', 'is_deleted'], name='adminpanel__offer_t_3e805c_idx'), models.Index(fields=['start_date', 'end_date'], name='adminpanel__start_d_2669db_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='offer_discount_value_gt_zero')],
            },
        ),
    ]
