# Generated by Django 6.0.5 on 2026-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount applicable only for percentage offers.', max_digits=12, null=True),
        ),
    ]
