# Generated by Django 6.0.5 on 2026-07-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_offer_max_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_discount_amount',
        ),
    ]
