# Generated by Django 6.0.5 on 2026-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
