# Generated by Django 6.0.5 on 2026-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_customuser_ip_address_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique referral code for this user.', max_length=12, null=True, unique=True),
        ),
    ]
