# Generated by Django 6.0.5 on 2026-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='INDIA', max_length=100),
        ),
    ]
