# Generated by Django 6.0.5 on 2026-06-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_wishlist_unique_together_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
