# Generated by Django 6.0.5 on 2026-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('ADD_MONEY', 'Add Money'), ('CANCEL_REFUND', 'Cancel Refund'), ('RETURN_REFUND', 'Return Refund'), ('WALLET_PAYMENT', 'Wallet Payment'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=30),
        ),
    ]
