# Generated by Django 6.0.5 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_wallettransaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('NETBANKING', 'Netbanking'), ('UPI', 'UPI'), ('WALLET', 'Wallet'), ('PAY_LATER', 'Pay Later')], max_length=20, null=True),
        ),
    ]
