# Generated by Django 6.0.5 on 2026-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('RAZORPAY', 'Razorpay'), ('CARD', 'Card'), ('NETBANKING', 'Netbanking'), ('UPI', 'UPI'), ('WALLET', 'Wallet'), ('PAY_LATER', 'Pay Later')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
