# Generated by Django 6.0.5 on 2026-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_wallettransaction_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('ADD_MONEY', 'Add Money'), ('CANCEL_REFUND', 'Cancel Refund'), ('RETURN_REFUND', 'Return Refund'), ('WALLET_PAYMENT', 'Wallet Payment'), ('REFERRAL_REWARD', 'Referral Reward'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=30),
        ),
    ]
