# Generated by Django 6.0.5 on 2026-07-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_returnrequest_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
