# Generated by Django 6.0.5 on 2026-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay'), ('UPI', 'UPI')], default='COD', max_length=20),
        ),
    ]
