# Generated by Django 6.0.5 on 2026-07-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_order_orderaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
